// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // 1. Logic to return the web config when running on Chrome
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 2. THIS IS THE MISSING WEB CONFIGURATION
  // I have used your project ID 'cashclashdroid'. 
  // NOTE: If this doesn't work, your friend needs to send you the actual Web 'apiKey' and 'appId'
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NxwSXtEDOrBPxdzN_Jht8wqZwDIa1QI', // Using your Android key as a placeholder
    appId: '1:400524815750:web:057bfa0e01b23c1fc11007', // Common web appId format
    messagingSenderId: '400524815750',
    projectId: 'cashclashdroid',
    authDomain: 'cashclashdroid.firebaseapp.com',
    storageBucket: 'cashclashdroid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6NxwSXtEDOrBPxdzN_Jht8wqZwDIa1QI',
    appId: '1:400524815750:android:057bfa0e01b23c1fc11007',
    messagingSenderId: '400524815750',
    projectId: 'cashclashdroid',
    storageBucket: 'cashclashdroid.firebasestorage.app',
  );
}